language: java
dist: trusty

before_install:
- cd BuildTools
- bash build-pre1.17.sh
- wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
- chmod +x $TRAVIS_BUILD_DIR/BuildTools/install-jdk.sh
# Installs Java 16 and runs scripts needing Java 16.
- export JAVA_HOME=$HOME/openjdk16
- $TRAVIS_BUILD_DIR/BuildTools/install-jdk.sh -F 16 --target $JAVA_HOME
- export PATH=$JAVA_HOME/bin:$PATH
- bash build-1.17.sh
# Installs Java 17 and runs scripts needing Java 17.
- export JAVA_HOME=$HOME/openjdk17
- $TRAVIS_BUILD_DIR/BuildTools/install-jdk.sh -F 17 --target $JAVA_HOME
- export PATH=$JAVA_HOME/bin:$PATH
- bash build-1.18+.sh
##
- cd ../

install:
- mvn -U clean install

script:
- mvn package -DskipTests

cache:
  directories:
  - $HOME/.m2
  - BuildTools/Bukkit
  - BuildTools/Spigot
  - BuildTools/CraftBukkit
  - BuildTools/BuildData

before-deploy:
- export FOO=$(ls Server/plugins/ChestsPlusPlus-*.jar)

deploy:
  provider: releases
  skip_cleanup: true
  draft: true
  api_key:
    secure: PQ5CocKxo9VifO+yJzTPHGgbRZT5tOu2sWLLov6yvwkIRyItb2xAmdpyNUlJq2XrtEUaZFRgrioiSFcujriRFMQ0zSvPz3JYPaUwkp/98ljLobNJwGLyzj4IUJrdXPQnq/DLNm5GEwxuzWqRl+3RemEeZsm6cPf8hQY1QKeJIa8FnwH0hjmaDQSRq7GQDpsN3XIqwClNoV3tgOvNa+7qXEfh4lQA78hnS3bX8GlHzuzV8rBW2ttzFSdeMcV+hnoGYN/dv8CnX+4mz0hNuwX+N1+5pgfnc2wKnAlUu6maYyTt9z71sX2lnGyoTh1Nq5rxbk36PuovYqlhqJhmgEGCtQnSILUpL1ndNDDl3zBMskZugA70/PuXL46y5vdsP9zqTh0Q+xFsXx9zByIVEPSi8m2+F4MM6693i7OOm775cFFUB9G9NKpJnWcTmW0CG4yW0nYmyg8PnERe4uFsxCBk7iaEC7y4Gtk8XqasKDmLNrPxwWVN8bvRU5m2ai41WLgLS/Wnff3dOOlVftFjRVkjjSK5Gxcvb39DVITJyNabEqkYyeFBWw7MoL2pPJyICEyHt2bj6uLq92h5v8JDKI1eDBtoW341wLesaQMhqRW3UNbN9AOmA+saJQHR6WerNyKOBSaBhy/MdlfCvzycqIfuNx/BcVv3xLUodliFM2iwD8I=
  file: "${FOO}"
  on:
    tags: true
    repo: JamesPeters98/ChestsPlusPlus
